### ISSUE TITLE
[BUG] tablet.html does not display correctly on iPad

### ISSUE THREAD

**Issue by yurividal** [bitfocus/companion#1464]
![image](https://user-images.githubusercontent.com/8555749/109690108-e4854600-7b7d-11eb-9762-da560cba0808.png)

As seen on the screenshot above, the tablet.html does not render properly on 4x3 screens such as the iPad.
The Next page's buttons show on the bottom of the screen, and the last page is completely offset.

There is an easy fix:

add the following property to .page
```
padding-bottom: 125px;
```

so, it looks like this:
```
      .page {
        padding: 20px;
        padding-bottom: 125px;
      }
```

![image](https://user-images.githubusercontent.com/8555749/109690445-42b22900-7b7e-11eb-8f5b-5a3519a34631.png)

**Comment by krocheck** [comment]
Have you tried using the "Mobile buttons" interface, or `/tablet2.html`?  I think the plan is to retire `/tablet.html` interface once we get around to making a few tweaks to the newer one.

**Comment by yurividal** [comment]
I have. But, personally, I find tablet2 to be a bit cluttered. Tablet.html provides a much cleaner interface and less changes for some operator to screw up. Especially because I save the bookmark with "?pages=1,2,3"
Which leads to a clean UI, with no extra buttons on anything I don't need.

**Comment by krocheck** [comment]
I see your point on clutter, but you can apply the page filtering just the same to tablet2.

**Comment by yurividal** [comment]
I know. Thanks. But yeah, tablet2 is a bit too cluttered for me. I am using a personal build with the fix I have suggested above. But, it would be an easy fix if the developers want to include it in the main build.

**Comment by yurividal** [comment]
Wow, just tested tablet2.html on the ipad and it is terrible. Not only its cluttered, but completely out of alignment. 
im gonna stick to tablet.html with my customization. 
![image](https://user-images.githubusercontent.com/8555749/109722191-46f13d00-7ba4-11eb-8459-6ab20358c76b.png)
![image](https://user-images.githubusercontent.com/8555749/109722253-5bcdd080-7ba4-11eb-86ec-0de5885ec762.png)


To make it worse, the down button goes to the previous page, and the up button goes to the next page. SUPER COUNTER-INTUITIVE.

**Comment by Julusian** [comment]
I don't think your fix is sufficient to be included.
It works on an ipad, but does not help on any other device with a different resolution.
Setting `min-height: 100vh` will be more generic, but that will be bad for users who prefer to use it as an infinite scrolling list.

Hopefully soon I can find time to build a new tablet page which is more configurable

**Comment by yurividal** [comment]
@Julusian I have customized tablet.html to fit better on iPads, and also have made the page-change buttons look nicer and cleaner.  The "back arrow" button gets greyed out on the first page, and the "forward arrow" gets greyed out on the last page.

![image](https://user-images.githubusercontent.com/8555749/109871659-52576d80-7c63-11eb-8fff-667cda1671a1.png)

![image](https://user-images.githubusercontent.com/8555749/109871958-ac583300-7c63-11eb-9e77-b590d7d8f4ed.png)




Maybe, if you guys want, you can add it to the base as ipad.html ?
This way, the original tablet.html is unchanged, and users of ipad can use this version.

**Comment by JeffreyDavidsz** [comment]
Of course it would be better to handle it in one file, but untill this happens I have no problem including a ipad.html please submit a pull request, I'll approve it

**Comment by yurividal** [comment]
> Of course it would be better to handle it in one file, but untill this happens I have no problem including a ipad.html please submit a pull request, I'll approve it

https://github.com/bitfocus/companion/pull/1471

**Comment by yurividal** [comment]
@JeffreyDavidsz  not sure if you want to include a direct link to it on the admin page side-bar, but that would be cool too.

**Comment by Julusian** [comment]
@yurividal I have merged your ipad variant.
I have also just merged in a new version of the view which I have written from scratch. The aim is to replace all the existing tablet versions with this when the legacy ui is removed, which will hopefully be sometime before the 2.2 release. At this point, your ipad variant will also break due to changes in how dependencies are handled. 
Could you give my new one a try and give me some feedback? I have tried to combine all the functionality in the existing views, and make some improvements. Hopefully the 'cycle' layout is suitable for what you want.

**Comment by yurividal** [comment]
@Julusian sorry, i've been off the grid for the past week. I looked into the current master branch, and didn't see this new version you mentioned. White file exactly  is it?

**Comment by Julusian** [comment]
No problem, Im not in a rush to get this done.
Its not a html file in the folder, the easiest way to get to it is to either go to `http://localhost:8000/tablet3`, replacing `localhost:8000` to be however you connect to the admin interface, or to switch to the new ui and click the web buttons link from there.

I do have some feedback I havent acted on yet, mainly some unintentional scrolling when in cycle mode, and long pressing not behaving on ios. So it is not finished yet, but is a reasonable representation of how it will ultimately look

**Comment by yurividal** [comment]
Sorry mate. I must be doing something wrong. Even after switching to the new ui, "web buttons" still take me to tablet.html
I'm not sure how to get to the new one you mentioned.
Just to be clear, it's on the master branch , right?

**Comment by yurividal** [comment]
Hi @Julusian i was able to finally test out the new table3 ui.
It indeed works fine on ipad, when you set it to "Cycle" mode. The "infinite" mode still shows part of the next page.
The fullscreen buttons doesn't seem to do anything, at least not on the ipad.
Other than that, it all just works and looks great! good job"

**Comment by yurividal** [comment]
@Julusian is there any way to achieve this same behaviour with v3?
I was using the ipad.html (improved tabled2.html) on v2.2, but since i updated to v3, i can no longer cycle between pages on my ipad.
