### ISSUE TITLE
[FEATURE] Triggers on button color.

### ISSUE THREAD

**Issue by Boguinhos** [bitfocus/companion#1612]
A general, maybe easy and effective way to cascade actions would be to set off a button press on a specific color change from another button. 
This could be achieved on the trigger section as an internal variable or even a drop down menu for making it easier.

**Usecases**
If button 1.1 is black (0,0,0) press 1.10. 
If button 1.1 is red (255,0,0) press 1.20.
This way, as most instances feedback are able to change a button's color, it would be possible to do some basic automations based on real feedbacks and it would be for available for general use.

**Comment by Julusian** [comment]
If anything is done here, it should be done as a boolean feedback based on another buttons colour.
Care will need to be taken to avoid an infinite loop.
Coupled with #1604 that will provide the desired functionality in a good way

**Comment by Boguinhos** [comment]
Hi Julusian. I've been checking out the latest beta release that you did some 15 hours ago "addUpgradeToBooleanFeedbackScript not returning a changed boolean". 
I have a very low programming skill and been trying to understand what's under the hood at companion but it's a bit out of my league. That being said, i've tested some trigger with internal variables, and trying to find a list of the complete internal variables that could be used in a trigger but i'm guessing these are dynamic and basically all the existing appear on a instance or button dropdown list, right? there isn't already a button color variable? 

Triggers seem to be triggering only once as the condition is met, at least with XR instance feedback for channel value. I'm guessing infinite loop could be avoided or controlled on an .emit event for button color changing or even on the trigger, with the possibility to state how many times that trigger is supposed to run.

Thanks for all.

**Comment by Julusian** [comment]
The latest beta doesn't have what you need for this ,there is no variable for it currently.

**Comment by Boguinhos** [comment]
That i've noticed. :) anyways i've checking out for , example: a audio fader level below "x" value as a trigger condition with an "and" for another trigger condition like audio fader level above "z" value and it's not looking like it's doing the "and" correctly. could it be that it's messing up the signed db value? like under -40 and above -50. 
And i am getting that triggers run every time the condition is met, even if it's the same condition that was already met before.

**Comment by Julusian** [comment]
Try using the opposite one of < and >. I believe I found a quirk where they are being applied the opposite way round to what you would expect.
I think I noticed that when reading the code too. This should be solved with #1604

**Comment by Boguinhos** [comment]
Also tried. And behaviour was still strange

**Comment by istnv** [comment]
> **Usecases**
> If button 1.1 is black (0,0,0) press 1.10.
> If button 1.1 is red (255,0,0) press 1.20.

This is not that simple as colors are not exact. 
What is 'Red' ? (250,0,0) will look the same but *not* match your test.

**Comment by Julusian** [comment]
@istnv yeah, I am still trying to figure out if I think this is a good idea.
With it possible for feedbacks to be referenced directly in the triggers (only the boolean style feedbacks), Im not sure when this would be necessary (assuming every module reviewed and converted their feedbacks)

**Comment by Boguinhos** [comment]
> @istnv yeah, I am still trying to figure out if I think this is a good idea.
> With it possible for feedbacks to be referenced directly in the triggers (only the boolean style feedbacks), Im not sure when this would be necessary (assuming every module reviewed and converted their feedbacks)

Yes, that is it. If every module had all the possible imaginary feedback, it would be ok. But turning to color could make it kind of the “gpio” of companion. The emergency multi purpose solution when you need something that still does not exist. 
And i’ve read somewhere that module update is going to change on v3.0 of companion so that updates can be released other way than a full stable build but until then this could be handy. I know i have use for it!

@istnv yeah i understand what you are saying but i guess that is a good thing if you pick a rgb specific value.

**Comment by istnv** [comment]
@Julusian I need to get familiar with the boolean feedback. Is it possible to add a boolean/flag at the same time a color changes? That would be more reliable than trying to guess which 'Red'.

**Comment by istnv** [comment]
@Boguinhos I rarely set 'full' colors. An example is the preset for 'mute' red in the XR module sets the color to (128,0,0).

**Comment by Julusian** [comment]
@istnv the idea with boolean feedbacks is that the module only outputs true or false for those feedbacks. When on a button, the impact it has on the stly is up to companion and the user. 
The ui will look like this, with only the Input and M/E fields defined by the module.
![image](https://user-images.githubusercontent.com/1327476/115449414-b1bd0d00-a212-11eb-8b88-4f458ce07980.png)

Which means the triggers system can reuse the same feedbacks, and use the resuling true/false value in its own way. And simply not show the style bits of the ui 
![image](https://user-images.githubusercontent.com/1327476/120041497-40862c00-c000-11eb-8b7f-a508f6692a44.png)

Hopefully this explained well enough. The PR might give some more information https://github.com/bitfocus/companion/pull/1571 or you could skim the changes I made to use it in a module https://github.com/bitfocus/companion-module-homeassistant-server/commit/f969f9f725ea6aa1af52f2773aa09b1b8e10fee5#diff-e6c8dab39e2dcea6882ed534980280aab6cd0598033b8291d1da771e7ce9fde7 (I believe this is the shortest one I did)

**Comment by Boguinhos** [comment]
> @Boguinhos I rarely set 'full' colors. An example is the preset for 'mute' red in the XR module sets the color to (128,0,0).

That is the perfect example. In my opinion, if you would trigger on color change as you said, if you have another button for toggling mute on a specific channel it would be easy to trigger an unwanted action. Say i have a tally that wants to display green when muted and red when opened. If everytime that the mute is toggled triggers a color change but not a specific color how could i trigger a http request for red tally and another for green tally without latching it to a specific color on the button? If i explained myself clearly.

**Comment by Julusian** [comment]
I still don't think this is a good idea for us to do.
It would be better to get modules to use the boolean style feedback, or to expose variables which can be used for the triggers instead.

If we implement this, then it will be very hard to remove it later on without breaking things for users, and I suspect will make it hard to do other changes to how buttons render or feedbacks work without breaking it
