### ISSUE TITLE
[BUG] Pages Changing slowly on Companion Pi

### ISSUE THREAD

**Issue by flo10696** [bitfocus/companion#1882]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey All!

I installed Companion Pi on a Rapsberry Pi 4 (4GB) and noticed that the buttons do not refresh instantly when changing pages. It gets worse when there are pages packed with buttons. But when I look at the system resources of the Pi neither the memory nor the cpu seem to be the limiting factor. 

If you quickliy go through the pages it even skips some pages. 

Is there maybe some intentional slowing down due to compatibility and if so is there an option to deactivate that?

Thanks a lot!

### Environment (please complete the following information)

```markdown
- OS:CompanionPi-2021-07-25.img.gz
- Rapsberry Pi 4, 4GB Version
- 64GB SD Card UHS Class 1
```

**Comment by Julusian** [comment]
What model of streamdeck are you using? make sure it is plugged directly into one of the usb3 ports (the blue ones)

It is possible that the jpeg encoding library failed to install, causing it to use the slower method, but could be something else

**Comment by flo10696** [comment]
Thanks for the fast reply!

I used a Streamdeck XL as well as an "normal" streamdeck. Connected to USB 3 Port  but that shouldn't make a difference as the Streamdecks ports are only USB 2 or am I wrong there?

How would you install the jpeg encoding library manually?

**Comment by dszoka** [comment]
The XL deck must be in USB 3 port… 
Try that 1st then if you still have issues, backup your config and do a fresh install

**Comment by Julusian** [comment]
> How would you install the jpeg encoding library manually?

That depends on why it didnt install in the first place. It could have been a glitch meaning running `yarn` in /usr/local/src/companion will resolve it, or it could be it failed due to some missing dependency or platform mismatch which is hard to figure out without seeing the build error and some trial and error.

But it looks like the library is there on that companionpi image, so unless it broke following a `companion-update`, then I dont know why it would be so slow.

That said, I do remember when I was using a pi that page changes were slower than I would have liked. It wasnt too bad, but it was noticable. That is an unfornate limitation in either cpu or usb throughput on those devices that needs an in depth investigation to figure out how we can make it perform better

**Comment by jsnyder886** [comment]
For what it's worth, I tried this a while back with my dual XL setup on a pi and everything you mentioned was my exact experience.  I initially thought it was power related, so I picked up an inline USB power meter and never went past 50-60% of the available power provided by the pi-certified power supply on my unit with BOTH XLs running.  However, the page changes were so slow it was not usable in my environment so I abandoned my attempts.  I figured I try again at some point in the future.

**Comment by flo10696** [comment]
So i tried it again and made sure that it was plugged into the USB 3.0 but the behavior does not change. The video shows what it looks like.

Has anyone more ideas what the reason could be or is it just not perfect implementation for the lower power of the Pi?

 [](url

https://user-images.githubusercontent.com/22889659/154522112-a862f3ad-c97b-4c33-b53e-6640798c91d2.MP4

)

**Comment by Julusian** [comment]
Yeah, from memory this looks a little bit slower than general pi slowness, but not enough to indicate that there is something wrong somewhere.
I should do another investigation into whether it can be improved,

**Comment by Julusian** [comment]
I have just given this a test on a pi4 myself, and am seeing a similar speed. My first thought on the library being missing makes it much much slower.

I had an idea that perhaps the other hid driver might perform better, and from a crude test, it looks like switching to hidraw instead of libusb makes a typical full panel draw take 80ms instead of 300ms.
It is possible that there is further work that can be done in the connection library to optimise too.

Neither of these sounds doable before 2.2 is released unfortonately, (the original version of the 15 key doesnt work with the other mode, and some other usb devices havent been tested with it) but I shall add it to the list to do for 2.3

**Comment by flo10696** [comment]
Hey @Julusian thanks so much for the effort of looking into the issue. Is there a way to switch the the hid driver ourselves so we could use that for our Prototype testing? 

It would be really great to see improvement in the speed because we see good potential for the use with the pi.

**Comment by Julusian** [comment]
I have pushed a change to make it be an opt-in feature to master. It turns out that since a little under 2 years ago, all models work with the faster backend.
In 2.3 or maybe a 2.2 patch release I will make it be the default, but I don't want to push it as default so close to the release of 2.2. 

To enable it, update to the latest master `sudo compnanion-update` 

Edit the system service file at `sudo nano /etc/systemd/system/companion.service`  
Adding the line `Environment="COMPANION_USE_HIDRAW=1"` after the line containing `[Service]`

Edit the file at `sudo nano /etc/udev/rules.d/50-companion.rules`
If there are no lines containing `KERNEL=="hidraw"`, then add this block to the bottom
```
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f41", MODE:="666", GROUP="plugdev"
```

Reboot and it should work.
If it somehow breaks streamdecks completely, undoing the change to the `/etc/systemd/system/companion.service` should be enough to disable the change

**Comment by flo10696** [comment]
Really great that you put so much work into helping us! Thanks a lot!

**Comment by flo10696** [comment]
I did the upgrade you suggested and the issue seems to be fixed but I know run into this issue. I can access the Admin Control Panel but its stuck in "syncing". undoing the change to '/etc/systemd/system/companion.service does not solve it. Any suggestions
![Bildschirmfoto 2022-03-04 um 18 37 18](https://user-images.githubusercontent.com/22889659/156813884-eb0356a9-d230-407a-a48e-455cc6569e5b.png)
?

**Comment by abebeos** [comment]
For the case you have a source-code installation:

I needed to run

```sh
./tools/update.sh
```

within the companion folder after switching to another version in order to fix the "Syncinc" problem.

**Comment by flo10696** [comment]
this may be a dumb question but when I'm trying to run './tools/update.sh' I just get an error stating that theres no such file or directory. I do not find the companion folder on my pi to run the command in.

**Comment by abebeos** [comment]
No worries.

This was "For the case you have a source-code installation".

You have possibly installed companion via an installer/package? Should be locatable by `whereis companion` within your shell.

If you find it, `cd` into `companion`, then  './tools/update.sh'

**Comment by abebeos** [comment]
(possibly reinstall from source, if you can risk it, see: https://github.com/bitfocus/companion/wiki/Companion-on-the-Raspberry-Pi)

**Comment by Julusian** [comment]
@abebeos CompanionPi is a prebuilt image for raspberry pi with companion preinstalled. The `companion-update` script is a pretty simple wrapper that calls the `./tools/update.sh` script

@flo10696 Could you try doing `sudo companion-update` again? Perhaps it failed on something?

**Comment by Julusian** [comment]
Having not heard back I'm assuming this has been resolved

**Comment by flo10696** [comment]
I haven‘t had the chance to test it again, I will try to do that in the next week, been working the last weeks. But I‘ll keep you updated!

**Comment by onfire4g05** [comment]
I've also tried this and it's not working for me, either. I've tried an XL and a Mini and Companion couldn't find either when `COMPANION_USE_HIDRAW=1` was used but can be found without.

**Comment by Julusian** [comment]
OK, I've had a look and you are right in that it doesnt work.
If you are using the 2022-03-30 companionpi image, then doing a `sudo companion-update` then reboot will fix it.
If you are on an older companionpi image, then replace the file `/etc/udev/rules.d/50-companion.rules` (I might be slightly off on exact filename, but it will be similar in that folder) with the contents of https://github.com/bitfocus/companion-pi/blob/main/50-companion.rules and then reboot.

**Comment by onfire4g05** [comment]
That fixed it, thanks!! I did try that when trying to figure out the issue earlier... but I reloaded and didn't reboot. 🤦🏻‍♂️ I've found that reloads don't always work.

**Comment by Julusian** [comment]
Glad to hear!
A reload would work but needs to be followed by unplugging and reconnecting the device
