### ISSUE TITLE
Companion not auto-detecting new websocket

### ISSUE THREAD

**Issue by brandenman** [bitfocus/companion#996]
Software:
OBS - v24.0.3
obs-websocket: v4.7.0
Bitfocus Companion: v1.3

I'm having an issue where if Companion is open before OBS, after opening OBS Companion does not detect the new websocket is connected, and requires a manual restart of Companion before I can control OBS.

The current workaround:
1. Open OBS
2. Verify the Websocket plug-in is on (it's on by default)
3. Close Companion if it is open
4. Re-open Companion
5. Wait for Alert showing that the OBS websocket is connected (usually immediately)

**Comment by josephdadams** [comment]
Are you still running Companion 1.3? At least move to 1.4, but I’m fairly certain this has been fixed in 2.0. Please try 2.0 and report back.

**Comment by josephdadams** [comment]
Also you can disable the OBS instance in Companion and re enable it for a quicker fix on your current setup.

**Comment by josephdadams** [comment]
@brandenman ?

**Comment by brandenman** [comment]
I just tested 2.0 and it looks like that resolved the obs issue but it does
have the scaling issues with the smaller streamdecks, I’m installing 1.4
now and will keep you posted

**Comment by brandenman** [comment]
Reinstalled 1.4 and it is having the issue still, if companion is open
before OBS, it will not detect the obs websocket and the obs control
buttons do not work until I manually reboot companion with OBS already open

**Comment by josephdadams** [comment]
I’ll close this since it’s fixed in 2.0. I use OBS as well and have the same issue in earlier versions. For me, it works to just disable and enable the instance rather than to restart Companion completely, if you’d like to consider that if you want to stay on 1.4.
